# Generated by Django 2.2.6 on 2020-03-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_user_id', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('home_user_id', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('home_team_id', models.IntegerField()),
                ('penalty_shootout', models.BooleanField()),
                ('date_played', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_team_id', models.IntegerField()),
                ('nick_name', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Game')),
            ],
        ),
        migrations.CreateModel(
            name='CupGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Cup')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='userprofile.Game')),
                ('prev_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_game', to='userprofile.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenged_id', models.IntegerField()),
                ('challenger_id', models.IntegerField()),
                ('proposed_date', models.DateTimeField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Game')),
            ],
        ),
    ]
