# Generated by Django 2.2.6 on 2020-03-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cup',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Name',
            new_name='name',
        ),
    ]
