# Generated by Django 2.2.6 on 2019-11-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='fullapp_game',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='fullapp_profile',
        ),
        migrations.AlterModelTable(
            name='team',
            table='fullapp_team',
        ),
    ]
