# Generated by Django 2.2.6 on 2020-04-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200330_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='version',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='challenged_id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='challenger_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_user_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_user_id',
        ),
        migrations.RemoveField(
            model_name='league',
            name='game',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenged',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenged_user', to='userprofile.Profile', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenger_user', to='userprofile.Profile', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='userprofile.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_user', to='userprofile.Profile', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='userprofile.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_user', to='userprofile.Profile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_game', to='userprofile.Game'),
        ),
        migrations.AlterField(
            model_name='cupgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_game', to='userprofile.Game'),
        ),
        migrations.CreateModel(
            name='LeagueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_game', to='userprofile.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='userprofile.League')),
            ],
        ),
    ]
