# Generated by Django 3.0.5 on 2020-04-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200409_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='cupgame',
            name='prev_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_game', to='userprofile.Game'),
        ),
    ]
