# Generated by Django 2.2.6 on 2020-04-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200402_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pointsss',
            new_name='points',
        ),
        migrations.AddField(
            model_name='league',
            name='is_two_leg',
            field=models.BooleanField(default=True),
        ),
    ]
